// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sys} from '../models';
import {runtime} from '../models';

export function GetCPUUsage():Promise<sys.CPUUsage>;

export function GetDISKUsage():Promise<sys.DISKUsage>;

export function WailsInit(arg1:runtime.Runtime):Promise<void>;
