// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUUsage() {
  return window['go']['sys']['Stats']['GetCPUUsage']();
}

export function GetDISKUsage() {
  return window['go']['sys']['Stats']['GetDISKUsage']();
}

export function GetMemoryUsage() {
  return window['go']['sys']['Stats']['GetMemoryUsage']();
}

export function WailsInit(arg1) {
  return window['go']['sys']['Stats']['WailsInit'](arg1);
}
